insert into U_Item(num,ItemText,ItemValue) values('12','总行委贷','是,否') 
insert into U_Item(num,ItemText,ItemValue) values('13','企业经营状况','良好,维持,停业,注销,破产') 
insert into U_Item(num,ItemText,ItemValue) values('14','地区经济与信用状况','好,中,较差,差') 
insert into U_Item(num,ItemText,ItemValue) values('15','企业规模','大,中,小') 
insert into U_Item(num,ItemText,ItemValue) values('16','企业经济性质','国有,集体,股份,有限,民营,其他')
insert into U_Item(num,ItemText,ItemValue) values('17','债务人有效资产状况','不详,有,无,差,极差')
insert into U_Item(num,ItemText,ItemValue) values('18','保证有效性','有效,无效')
insert into U_Item(num,ItemText,ItemValue) values('19','保证人的偿债能力','高,中,低')
insert into U_Item(num,ItemText,ItemValue) values('20','保证人的偿债意愿','强,一般,弱')
insert into U_Item(num,ItemText,ItemValue) values('21','抵押物取得是否存在障碍','是,否')
insert into U_Item(num,ItemText,ItemValue) values('22','抵押物处置是否存在障碍','是,否')
insert into U_Item(num,ItemText,ItemValue) values('23','抵押物变现难易','难,一般,易')
insert into U_Item(num,ItemText,ItemValue) values('24','抵押物法律意见','有效,无效')
insert into U_Item(num,ItemText,ItemValue) values('25','质押物取得是否存在障碍','是,否')
insert into U_Item(num,ItemText,ItemValue) values('26','质押物处置是否存在障碍','是,否')
insert into U_Item(num,ItemText,ItemValue) values('27','质押物变现难易','难,一般,易')
insert into U_Item(num,ItemText,ItemValue) values('28','质押物法律意见','有效,无效')
insert into U_Item(num,ItemText,ItemValue) values('29','质押物类别','存单,股票,国债,有价单证,其他')
insert into U_Item(num,ItemText,ItemValue) values('30','抵押物类别','房产,土地,车辆,生产设备,产成品,其他')
insert into U_Item(num,ItemText,ItemValue) values('31','管辖','武昌,汉口')
insert into U_Item(num,ItemText,ItemValue) values('32','抵债物资类别','存单,股票,国债,有价单证,房产,土地,车辆,生产设备,产成品,其他')

alter table U_ZC add gx nvarchar(50)
alter table U_ZCTC add status nvarchar(50)
alter table U_UserName add Phone nvarchar(50)
insert into U_Roles(num,Role,remark) values('11','财务数据浏览','可以对财务数据进行浏览')
alter table U_ZC add Bstatus nvarchar(50)
alter table U_ZCBAO add Bzeren nvarchar(50)
alter table U_ZCBAO add Bstatus nvarchar(50)
alter table U_ZCTC add Bkind nvarchar(2)
alter table U_ZCFiles add Bkind nvarchar(2)