CREATE TABLE [dbo].[U_OLDZC] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[num2] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[danwei] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[bj] [numeric](18, 2) NULL ,
	[lx1] [numeric](18, 2) NULL ,
	[lx2] [numeric](18, 2) NULL ,
	[lx3] [numeric](18, 2) NULL ,
	[quyu] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[guangxia] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[bank] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[sshy] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[depart] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[zeren] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[zhwd] [nvarchar] (2) COLLATE Chinese_PRC_CI_AS NULL ,
	[num1] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[zcbao] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[zhuang] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[htnum] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[time0] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[fenlei] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[remark] [nvarchar] (200) COLLATE Chinese_PRC_CI_AS NULL ,
	[huobi] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[huilv] [numeric](18, 5) NULL ,
	[status] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[userkind] [nvarchar] (500) COLLATE Chinese_PRC_CI_AS NULL ,
	[zzjg] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[jysfzc] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[clsj] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[zczb] [numeric](18, 2) NULL ,
	[dqjj] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[qygm] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[dwdz] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[dwfzr] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[qyjjxz] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[yxzzzk] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[xdri] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[dkffrq1] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[jklsh] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[dkye] [numeric](18, 2) NULL ,
	[dkffrq2] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[htdqr] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[zjycszje] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[zydbfs] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[dbrwmc] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[yyldxt] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[xcyqrq] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[jrblsj] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[xgr] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
	[xgsj] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
	[zcid] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO